# Generated by Django 3.0.6 on 2020-10-01 16:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(verbose_name='Content')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Date of timestamp')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_moderation', 'In moderation'), ('rejected', 'Rejected'), ('published', 'Published')], max_length=40, verbose_name='title')),
                ('grade', models.PositiveIntegerField(help_text='Validate project from 1 - 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(11)], verbose_name='grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(help_text='Validate project from 1 - 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(11)], verbose_name='grade')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='works.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
    ]
