# Generated by Django 3.0.5 on 2020-10-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20201002_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(max_length=300, verbose_name='Content'),
        ),
    ]
