# Generated by Django 3.0.5 on 2020-10-02 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201002_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveIntegerField(help_text='Validate project from 1 - 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='grade'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.PositiveIntegerField(help_text='Validate project from 1 - 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)], verbose_name='grade'),
        ),
    ]
