# Generated by Django 3.0.6 on 2020-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
                ('description', models.TextField(blank=True, verbose_name='Descritpion')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of project', max_length=50, verbose_name='Project name')),
                ('description', models.CharField(help_text='Name of project', max_length=250, verbose_name='Project descripton')),
                ('date_of_create', models.DateField(blank=True, null=True, verbose_name='Date of create')),
                ('web_site', models.URLField(blank=True, verbose_name='Web site Address')),
                ('portfolio', models.ImageField(blank=True, default='', upload_to='', verbose_name='Cover_image')),
                ('categories', models.ManyToManyField(to='works.Category', verbose_name='Categories')),
            ],
        ),
    ]
