# Generated by Django 3.0.5 on 2020-10-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Name of project', verbose_name='Project descripton'),
        ),
    ]
